{% set python_min = "3.11" %}
{% set name = "multispaeti" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multispaeti-{{ version }}.tar.gz
  sha256: 6b0e16db9b79cc0ba12b74ce538dfa6a207f91dbdb271ba6b2bdaa3f0d5a9534

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8
    - numpy >=1.25
    - scikit-learn >=1.6
    - scipy >=1.11

test:
  imports:
    - multispaeti
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HiDiHlabs/multiSPAETI
  summary: Implementation of MULTISPATI-PCA in python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://multispaeti.readthedocs.io/

extra:
  recipe-maintainers:
    - niklasmueboe
