{% set python_min = "3.10" %}
{% set name = "multispaeti" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multispaeti-{{ version }}.tar.gz
  sha256: 841820724c12bc0d102699860cfaee8417bc90df0c9307e5645447ee25f1abec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.6
    - numpy >=1.23
    - scikit-learn >=1.1
    - scipy >=1.9

test:
  imports:
    - multispaeti
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HiDiHlabs/multiSPAETI
  summary: Implementation of MULTISPATI-PCA in python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://multispaeti.readthedocs.io/

extra:
  recipe-maintainers:
    - niklasmueboe
